# Generated by Django 5.0.7 on 2024-07-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyurtma',
        ),
    ]
